# Generated by Django 4.1.3 on 2022-11-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='cd_imovel',
            new_name='cd_anuncio',
        ),
    ]
